export enum ENUM_ORGANIZATION_STATUS_CODE_ERROR {
  ORGANIZATION_NOT_FOUND_ERROR = 8200,
  ORGANIZATION_ALREADY_LINKED_WITH_USER_ID = 8201,
  ORGANIZATION_ALREADY_EXIST_ERROR = 8202,
  ORGANIZATION_MOBILE_NUMBER_EXIST_ERROR = 8203,
  ORGANIZATION_IS_ACTIVE_ERROR = 8204,
  ORGANIZATION_INACTIVE_ERROR = 8205,
  ORGANIZATION_PASSWORD_NOT_MATCH_ERROR = 8206,
  ORGANIZATION_PASSWORD_NEW_MUST_DIFFERENCE_ERROR = 8208,
  ORGANIZATION_PASSWORD_ATTEMPT_MAX_ERROR = 8209,
  ORGANIZATION_BLOCKED_ERROR = 8210,
  ORGANIZATION_MISSING_ORGANIZATIONNAME_EMAIL_ERROR = 8211,
}
