export enum ENUM_ADDRESS_STATUS_CODE_ERROR {
  ADDRESS_NOT_FOUND_ERROR = 5200,
  ADDRESS_EXISTS_ERROR = 5201,
  ADDRESS_EMAIL_EXIST_ERROR = 5202,
  ADDRESS_MOBILE_NUMBER_EXIST_ERROR = 5203,
  ADDRESS_IS_ACTIVE_ERROR = 5204,
  ADDRESS_INACTIVE_ERROR = 5205,
  ADDRESS_PASSWORD_NOT_MATCH_ERROR = 5206,
  ADDRESS_PASSWORD_NEW_MUST_DIFFERENCE_ERROR = 5207,
  ADDRESS_PASSWORD_EXPIRED_ERROR = 5208,
  ADDRESS_PASSWORD_ATTEMPT_MAX_ERROR = 5209,
  ADDRESS_BLOCKED_ERROR = 5210,
  ADDRESS_MISSING_ADDRESSNAME_EMAIL_ERROR = 5211,
}
