export enum ENUM_ATTENDENCE_STATUS_CODE_ERROR {
  ATTENDENCE_NOT_FOUND_ERROR = 6200,
  ATTENDENCE_ALREADY_LINKED_WITH_USER_ID = 6201,
  ATTENDENCE_ID_EXIST_ERROR = 6202,
  ATTENDENCE_MOBILE_NUMBER_EXIST_ERROR = 6203,
  ATTENDENCE_IS_ACTIVE_ERROR = 6204,
  ATTENDENCE_INACTIVE_ERROR = 6205,
  ATTENDENCE_PASSWORD_NOT_MATCH_ERROR = 6206,
  ATTENDENCE_PASSWORD_NEW_MUST_DIFFERENCE_ERROR = 6207,
  ATTENDENCE_PASSWORD_EXPIRED_ERROR = 6208,
  ATTENDENCE_PASSWORD_ATTEMPT_MAX_ERROR = 6209,
  ATTENDENCE_BLOCKED_ERROR = 6210,
  ATTENDENCE_MISSING_ATTENDENCENAME_EMAIL_ERROR = 6211,
}
