export enum ENUM_TEACHER_STATUS_CODE_ERROR {
  TEACHER_NOT_FOUND_ERROR = 7200,
  TEACHER_ALREADY_LINKED_WITH_USER_ID = 6201,
  TEACHER_CNIC_EXIST_ERROR = 6202,
  TEACHER_MOBILE_NUMBER_EXIST_ERROR = 6203,
  TEACHER_IS_ACTIVE_ERROR = 6204,
  TEACHER_INACTIVE_ERROR = 6205,
  TEACHER_PASSWORD_NOT_MATCH_ERROR = 6206,
  TEACHER_PASSWORD_NEW_MUST_DIFFERENCE_ERROR = 6207,
  TEACHER_PASSWORD_EXPIRED_ERROR = 6208,
  TEACHER_PASSWORD_ATTEMPT_MAX_ERROR = 6209,
  TEACHER_BLOCKED_ERROR = 6210,
  TEACHER_MISSING_TEACHERNAME_EMAIL_ERROR = 6211,
}
