export enum ENUM_CURRICULUM_STATUS_CODE_ERROR {
  CURRICULUM_NOT_FOUND_ERROR = 6200,
  CURRICULUM_ALREADY_LINKED_WITH_SUBJECT_ID = 6201,
  CURRICULUM_CNIC_EXIST_ERROR = 6202,
  CURRICULUM_MOBILE_NUMBER_EXIST_ERROR = 6203,
  CURRICULUM_IS_ACTIVE_ERROR = 6204,
  CURRICULUM_INACTIVE_ERROR = 6205,
  CURRICULUM_PASSWORD_NOT_MATCH_ERROR = 6206,
  CURRICULUM_PASSWORD_NEW_MUST_DIFFERENCE_ERROR = 6207,
  CURRICULUM_PASSWORD_EXPIRED_ERROR = 6208,
  CURRICULUM_PASSWORD_ATTEMPT_MAX_ERROR = 6209,
  CURRICULUM_BLOCKED_ERROR = 6210,
  CURRICULUM_MISSING_CURRICULUMNAME_EMAIL_ERROR = 6211,
}
