export enum ENUM_SCHOOL_STATUS_CODE_ERROR {
  SCHOOL_NOT_FOUND_ERROR = 7200,
  SCHOOL_ALREADY_LINKED_WITH_USER_ID = 7201,
  SCHOOL_ALREADY_EXIST_ERROR = 7202,
  SCHOOL_MOBILE_NUMBER_EXIST_ERROR = 7203,
  SCHOOL_IS_ACTIVE_ERROR = 7204,
  SCHOOL_INACTIVE_ERROR = 7205,
  SCHOOL_PASSWORD_NOT_MATCH_ERROR = 7206,
  SCHOOL_PASSWORD_NEW_MUST_DIFFERENCE_ERROR = 7207,
  SCHOOL_PASSWORD_EXPIRED_ERROR = 7208,
  SCHOOL_PASSWORD_ATTEMPT_MAX_ERROR = 7209,
  SCHOOL_BLOCKED_ERROR = 7210,
  SCHOOL_MISSING_SCHOOLNAME_EMAIL_ERROR = 7211,
}
