export enum ENUM_STUDENT_STATUS_CODE_ERROR {
  STUDENT_NOT_FOUND_ERROR = 6200,
  STUDENT_ALREADY_LINKED_WITH_USER_ID = 6201,
  STUDENT_CNIC_EXIST_ERROR = 6202,
  STUDENT_MOBILE_NUMBER_EXIST_ERROR = 6203,
  STUDENT_IS_ACTIVE_ERROR = 6204,
  STUDENT_INACTIVE_ERROR = 6205,
  STUDENT_PASSWORD_NOT_MATCH_ERROR = 6206,
  STUDENT_PASSWORD_NEW_MUST_DIFFERENCE_ERROR = 6207,
  STUDENT_PASSWORD_EXPIRED_ERROR = 6208,
  STUDENT_PASSWORD_ATTEMPT_MAX_ERROR = 6209,
  STUDENT_BLOCKED_ERROR = 6210,
  // STUDENT_MISSING_STUDENTNAME_EMAIL_ERROR = 6211,
}
